services:

  frontend:
    build: ./frontend
    ports:
      - '5173:5173'
    env_file:
      - frontend/.env
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - '8000:8000'
    env_file:
      - backend/.env
    networks:
      - app-network
    depends_on:
      - database

  database:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - backend/.env
    volumes:
      - db-vol:/var/lib/postgresql/data
    networks:
      - app-network

  adminer:
    image: adminer:latest
    container_name: adminer
    environment:
      ADMINER_DEFAULT_SERVER: database
    restart: always
    ports:
      - '8080:8080'
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  db-vol:
    driver: local